# function available minimum required
availableFunctions:
  - eventVSEnvironmental
integratedFunctions:
  # web client integrated function configuration
  plotVarDemo:
    description: |
      A demo app that help you to compare wind data with field events
    label: "Compare environmental data with events"
